# Generated by Django 5.0.4 on 2024-04-20 08:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='название')),
                ('short_description', models.CharField(max_length=35, verbose_name=' краткое описание')),
                ('full_description', models.TextField(verbose_name='полное описание')),
                ('price', models.IntegerField(verbose_name='цена')),
                ('quantity', models.IntegerField(verbose_name='количество на складе')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='', verbose_name='фотография продукта')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_creation', models.DateField(auto_created=True, verbose_name='дата создания')),
                ('text_of_the_comment', models.CharField(max_length=200, verbose_name='текст комментария')),
                ('user_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('link_to_the_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onlain.product')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='img',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onlain.productimg'),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('age', models.IntegerField(blank=True)),
                ('surname', models.CharField(blank=True, max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
