# Generated by Django 5.0.4 on 2024-04-23 13:30

import django.db.models.deletion
import onlain.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlain', '0003_profile_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='comment',
            field=models.CharField(default=1, max_length=200, verbose_name='#[^\\r\\n]*'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='rating',
            field=models.IntegerField(blank=True, default=1, verbose_name=onlain.models.Rating),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='link_to_the_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment1', to='onlain.product'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user_link',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='product',
            name='img',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='img1', to='onlain.productimg'),
        ),
        migrations.AlterField(
            model_name='productimg',
            name='img',
            field=models.ImageField(blank=True, upload_to='', verbose_name='фотография продукта'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='link_to_the_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating1', to='onlain.product'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='user_link',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating2', to=settings.AUTH_USER_MODEL),
        ),
    ]
